### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by kantlivelong**
Hello :wave:

This PR adds container support! I wanted to try this out but preferred using a container over locally with the tgz. Haven't had a chance to test functionality yet but the container starts and I can login. This can be added to the pipeline to create (and maybe push?!) to a registry. Should also make supporting different cpu architectures easier.

Example build:
`docker build --build-arg=BACKEND_VERSION=v0.7.0 --build-arg=FRONTEND_VERSION=v0.7.0 -t legocerthub:v0.7.0 .`

Example run:
`docker run -d --name legocerthub -p 4050:4050 -p 4060:4060 legocerthub:v0.7.0`

Additional volumes/binds will likely make sense on exec. IE:
`docker run -d --name legocerthub -v /some/local/path/config.yaml:/app/config.yaml -p 4050:4050 -p 4060:4060 legocerthub:v0.7.0`

Cheers :beers:

### CODE REVIEW

**Comment by gregtwallace** [comment]
They both build completely independently.

**Comment by gregtwallace** [comment]
I think a slight revision:
```
RUN sh -c "mkdir /app/data"
RUN sh -c "printf \"%s\n\" \
  \"'bind_address': ''\" \
  \"'hostname': 'localhost'\" \
  > \
  /app/data/config.yaml"

EXPOSE 4050/tcp
EXPOSE 4055/tcp
EXPOSE 4060/tcp
```

The other issue that dawned on me is that hostname should really be specified.  localhost is a decent starting place but only if the user is accessing the app initially from the same host.  I'm not sure the best way to get the proper fqdn into the config at the outset.

Any ideas?  Alternatively, could just warn users to edit config.yaml before first run (which they should probably be doing anyway).

**Comment by kantlivelong** [comment]
What is `hostname` used for (other than possibly previously being used as the bind address)? Sorry if is a stupid question I haven't had time to even set this up yet. :laughing: 

Hostnames can be set in containers but it's usually the exception rather than the rule.

One option a lot of apps will do is accept both config value or environment variables. Something like `LEGOCERTHUB_BIND_ADDRESS`, `LEGOCERTHUB_HOSTNAME`, etc...

**Comment by gregtwallace** [comment]
The fronted has an env.is file that contains a variable to set the url for the backend. Essentially the front end React app loads on the users’ computer and then makes api calls to that url.

When the back end hosts the front end it creates env.js on startup. The url is constructed with the host name.

I broke out bind address because I wanted to be able to specify a specific address that might not necessarily be the client resolvable fqdn.

**Comment by gregtwallace** [comment]
The fronted has an env.is file that contains a variable to set the url for the backend. Essentially the front end React app loads on the users’ computer and then makes api calls to that url.

When the back end hosts the front end it creates env.js on startup. The url is constructed with the host name.

I broke out bind address because I wanted to be able to specify a specific address that might not necessarily be the client resolvable fqdn.

**Comment by kantlivelong** [comment]
Would it make sense to have the react app listen at / and then have the backend be routed through /api? No need to even know the hostname/FQDN then.

**Comment by gregtwallace** [comment]
I don't know why I didn't think of the most obvious answer.

Fixed: https://github.com/gregtwallace/legocerthub-backend/commit/5adfa6ec2c68e43eed489add7ab44a0389df2df3

The additional port should still be exposed though.

**Comment by kantlivelong** [comment]
Nice! I've rebased from `master`, adjusted the bind var, added the additional tcp port. and squashed my commits.

**Comment by gregtwallace** [comment]
My bad, I also forgot the config path needs to be updated to /app/data

You could also update the bins address to blank which will ensure binding to both IPv4 and IPv6. 

I’ll merge this tonight with those tweaks. I’ll probably wait on the next release until I add an update check functionality.

**Comment by kantlivelong** [comment]
Pushed, hopefully that's what you were referring to :smile:

**Comment by gregtwallace** [comment]
Got it, thanks!

**Pull request merged**
